name: "CI-TestBuild"
on: [pull_request, push]

jobs:
    test-tauri:
        strategy:
            fail-fast: false
            matrix:
                platform: [macos-latest, ubuntu-20.04, windows-latest]

        runs-on: ${{ matrix.platform }}
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2.2.4
              with:
                  version: 8.3.0
            - name: setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: "pnpm"
            - name: install Rust nightly
              uses: dtolnay/rust-toolchain@nightly
            - name: install dependencies (ubuntu only)
              if: matrix.platform == 'ubuntu-20.04'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
            - name: install frontend dependencies
              run: pnpm install # change this to npm or yarn depending on which one you use
            - uses: tauri-apps/tauri-action@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
